### PR TITLE
Setup ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Hello @kiwanami  :smiley: 

I end up on your framework looking for an easy way to build emacs interface.

I was thinking about continuing the work you started, 
So I started up to put CI with [cask-package-toolset](https://github.com/AdrieanKhisbe/cask-package-toolset.el)

:)

### CODE REVIEW

**Comment by kiwanami** [comment]
Thank you!
This project is alive. Though I have little time to touch my projects, I'm using them every days.

Your project cask-package-toolset is great for emacs testing.

**Comment by AdrieanKhisbe** [comment]
You're welcome @kiwanami  :)

Just two little things to complete the PR
- can you tag a stable version? so that it is available on stable.melpa
- and log with github to coveralls to activate the coverage stats:  https://coveralls.io/r/kiwanami/emacs-widget-mvc

------ 
I didn't imply it was dead!! :smiley:, was wondering if I could intervene without walking over current development 
-------

About *cpt*, Thanks for your compliment :)
I'm open to feedback, suggestions, Pull request and stars  :)

**Comment by kiwanami** [comment]
OK, I tagged my last commit with v0.0.2. I would make the next tag after including your PR.
I added this repository at coveralls.io.
Thank you for your advice!

**Comment by AdrieanKhisbe** [comment]
you're welcome :)

**Pull request merged**
